### ISSUE TITLE
Loading images via <attachment>_data_uri on fixtures is not working

### ISSUE THREAD

**Issue by pablocrivella** [janko-m/shrine#117]
### Details

shrine gem version:  2.3.1
ruby version: 2.3.1
rails: 5.0.0.1

config/shrine.rb
```ruby
require 'shrine'
require 'shrine/storage/file_system'

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/cache'),
  store: Shrine::Storage::FileSystem.new('public', prefix: 'uploads/store')
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :determine_mime_type
Shrine.plugin :validation_helpers
Shrine.plugin :data_uri

```

app/models/image_block.rb
```
class ImageBlock < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :page
end
```

app/uploaders/image_uploader.rb
```ruby
require 'image_processing/mini_magick'

class ImageUploader < Shrine
  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions

  process(:store) do |io, _context|
    original = io.download
    large    = resize_to_fill(original, 1400, 660, gravity: 'North')
    medium   = resize_to_fill(original, 700, 400, gravity: 'North')
    small    = resize_to_fill(original, 350, 200, gravity: 'North')

    { original: original, large: large, medium: medium, small: small }
  end

  Attacher.validate do
    validate_mime_type_inclusion %w(image/jpeg image/png image/gif), message: I18n.t('errors.messages.invalid_image')
  end
end
```

fixture file
```yaml
about_main_image:
  page: about
  identifier: about_main_image
  image_data_uri: "data:image/png;base64,<%= Base64.encode64(File.binread("app/assets/images/homepage_header.jpg")) %>"
```

Exception message
```
ActiveRecord::Fixture::FixtureError: table "image_blocks" has no column named "image_data_uri".
```

**Comment by janko-m** [comment]
@pablocrivella Oh, that is unfortunate, I expected that fixtures will use the ActiveRecord model, but they seem to insert records directly. This is not a bug with Shrine, but just how fixtures work. So we'll have the find another way to setup Shrine with fixtures, though I think I'm out of ideas.

**Comment by pablocrivella** [comment]
@janko-m Oh that's too bad :( but thank you very much for letting me know! If i find a work-around i'll post it here!

**Comment by pablocrivella** [comment]
@janko-m just throwing and idea out there (probably it won't make sense since i haven't take a good look of the actual implementation)

Would it be possible to implement a method that would return the data that needs to be stored?
Something like this:

```yaml
about_main_image:
  page: about
  identifier: about_main_image
  image_data: "<%= Attacher.data_for(:image, File.open('image/path')) %>"
```
